[project]
name = "mini-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.2",
    "djangorestframework>=3.16.0",
    "drf-spectacular>=0.28.0",
    "drf-yasg>=1.21.10",
]

[project.optional-dependencies]
dev = [
    "django-stubs",
    "djangorestframework-stubs"
]


[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = false


[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

#[tool.mypy]
#plugins = ["mypy_django_plugin.main"]
#python_version = 3.12
#strict = true
#ignore_missing_imports = true
#exclude = ["migrations"]

[tool.django-stubs]
django_settings_module = "config.settings"
strict_settings = true