# Generated by Django 5.2.2 on 2025-06-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
