# Generated by Django 5.2.3 on 2025-06-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_user_nickname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
